/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-29 07:32:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.demo6;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/tags/addressInfo.tag", Long.valueOf(1693294342096L));
    _jspx_dependants.put("/WEB-INF/tags/hi.tag", Long.valueOf(1693293902134L));
    _jspx_dependants.put("/WEB-INF/tags/hello.tag", Long.valueOf(1693292785237L));
    _jspx_dependants.put("/WEB-INF/tags/add.tag", Long.valueOf(1693294182539L));
    _jspx_dependants.put("/WEB-INF/tlds/customtags.tld", Long.valueOf(1693291180518L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>Index Demo 6</h1>\r\n");
      out.write("	");
      if (_jspx_meth_ct_005fHello_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	");
      if (_jspx_meth_ct_005fHello_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	");
      if (_jspx_meth_ct_005ftag1_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	");
      if (_jspx_meth_ct_005ftag1_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	");
      if (_jspx_meth_ct_005fadd_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	");
      if (_jspx_meth_ct_005fadd_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	");
      if (_jspx_meth_ct_005fupper_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_ct_005fcategory_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<h3>JSP Tag</h3>\r\n");
      out.write("	");
      if (_jspx_meth_ct2_005fhello_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	");
      if (_jspx_meth_ct2_005fhi_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	");
      if (_jspx_meth_ct2_005fadd_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	\r\n");
      out.write("	");
      if (_jspx_meth_ct2_005faddressInfo_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_ct_005fHello_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ct:Hello
    com.demo.customtags.HelloTag _jspx_th_ct_005fHello_005f0 = new com.demo.customtags.HelloTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_ct_005fHello_005f0);
    try {
      _jspx_th_ct_005fHello_005f0.setJspContext(_jspx_page_context);
      _jspx_th_ct_005fHello_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ct_005fHello_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_ct_005fHello_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ct:Hello
    com.demo.customtags.HelloTag _jspx_th_ct_005fHello_005f1 = new com.demo.customtags.HelloTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_ct_005fHello_005f1);
    try {
      _jspx_th_ct_005fHello_005f1.setJspContext(_jspx_page_context);
      _jspx_th_ct_005fHello_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ct_005fHello_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_ct_005ftag1_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ct:tag1
    com.demo.customtags.Tag1 _jspx_th_ct_005ftag1_005f0 = new com.demo.customtags.Tag1();
    _jsp_getInstanceManager().newInstance(_jspx_th_ct_005ftag1_005f0);
    try {
      _jspx_th_ct_005ftag1_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/demo6/index.jsp(19,1) name = fullName type = String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ct_005ftag1_005f0.setFullName("Tuan Anh");
      _jspx_th_ct_005ftag1_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ct_005ftag1_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_ct_005ftag1_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ct:tag1
    com.demo.customtags.Tag1 _jspx_th_ct_005ftag1_005f1 = new com.demo.customtags.Tag1();
    _jsp_getInstanceManager().newInstance(_jspx_th_ct_005ftag1_005f1);
    try {
      _jspx_th_ct_005ftag1_005f1.setJspContext(_jspx_page_context);
      // /WEB-INF/views/demo6/index.jsp(21,1) name = fullName type = String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ct_005ftag1_005f1.setFullName("Thai Anh");
      _jspx_th_ct_005ftag1_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ct_005ftag1_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_ct_005fadd_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ct:add
    com.demo.customtags.AddTag _jspx_th_ct_005fadd_005f0 = new com.demo.customtags.AddTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_ct_005fadd_005f0);
    try {
      _jspx_th_ct_005fadd_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/demo6/index.jsp(23,1) name = number1 type = int reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ct_005fadd_005f0.setNumber1(15);
      // /WEB-INF/views/demo6/index.jsp(23,1) name = number2 type = int reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ct_005fadd_005f0.setNumber2(25);
      _jspx_th_ct_005fadd_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ct_005fadd_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_ct_005fadd_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ct:add
    com.demo.customtags.AddTag _jspx_th_ct_005fadd_005f1 = new com.demo.customtags.AddTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_ct_005fadd_005f1);
    try {
      _jspx_th_ct_005fadd_005f1.setJspContext(_jspx_page_context);
      // /WEB-INF/views/demo6/index.jsp(25,1) name = number1 type = int reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ct_005fadd_005f1.setNumber1(95);
      // /WEB-INF/views/demo6/index.jsp(25,1) name = number2 type = int reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ct_005fadd_005f1.setNumber2(25);
      _jspx_th_ct_005fadd_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ct_005fadd_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_ct_005fupper_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ct:upper
    com.demo.customtags.UpperTag _jspx_th_ct_005fupper_005f0 = new com.demo.customtags.UpperTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_ct_005fupper_005f0);
    try {
      _jspx_th_ct_005fupper_005f0.setJspContext(_jspx_page_context);
      _jspx_th_ct_005fupper_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_ct_005fupper_005f0, null));
      _jspx_th_ct_005fupper_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ct_005fupper_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_ct_005fcategory_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ct:category
    com.demo.customtags.CategoryTag _jspx_th_ct_005fcategory_005f0 = new com.demo.customtags.CategoryTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_ct_005fcategory_005f0);
    try {
      _jspx_th_ct_005fcategory_005f0.setJspContext(_jspx_page_context);
      _jspx_th_ct_005fcategory_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ct_005fcategory_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_ct2_005fhello_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ct2:hello
    org.apache.jsp.tag.web.hello_tag _jspx_th_ct2_005fhello_005f0 = new org.apache.jsp.tag.web.hello_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_ct2_005fhello_005f0);
    try {
      _jspx_th_ct2_005fhello_005f0.setJspContext(_jspx_page_context);
      _jspx_th_ct2_005fhello_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ct2_005fhello_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_ct2_005fhi_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ct2:hi
    org.apache.jsp.tag.web.hi_tag _jspx_th_ct2_005fhi_005f0 = new org.apache.jsp.tag.web.hi_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_ct2_005fhi_005f0);
    try {
      _jspx_th_ct2_005fhi_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/demo6/index.jsp(33,1) name = fullName type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ct2_005fhi_005f0.setFullName("Tuan Anh");
      _jspx_th_ct2_005fhi_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ct2_005fhi_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_ct2_005fadd_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ct2:add
    org.apache.jsp.tag.web.add_tag _jspx_th_ct2_005fadd_005f0 = new org.apache.jsp.tag.web.add_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_ct2_005fadd_005f0);
    try {
      _jspx_th_ct2_005fadd_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/demo6/index.jsp(35,1) name = num1 type = java.lang.Double reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ct2_005fadd_005f0.setNum1(java.lang.Double.valueOf("1"));
      // /WEB-INF/views/demo6/index.jsp(35,1) name = num2 type = java.lang.Double reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ct2_005fadd_005f0.setNum2(java.lang.Double.valueOf("6"));
      _jspx_th_ct2_005fadd_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ct2_005fadd_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_ct2_005faddressInfo_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ct2:addressInfo
    org.apache.jsp.tag.web.addressInfo_tag _jspx_th_ct2_005faddressInfo_005f0 = new org.apache.jsp.tag.web.addressInfo_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_ct2_005faddressInfo_005f0);
    try {
      _jspx_th_ct2_005faddressInfo_005f0.setJspContext(_jspx_page_context);
      javax.servlet.jsp.tagext.JspFragment _jspx_temp0 = new Helper( 1, _jspx_page_context, _jspx_th_ct2_005faddressInfo_005f0, null);
      // /WEB-INF/views/demo6/index.jsp(38,1) name = content type = null reqTime = true required = false fragment = true deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ct2_005faddressInfo_005f0.setContent(_jspx_temp0);
      _jspx_th_ct2_005faddressInfo_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ct2_005faddressInfo_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write('a');
      out.write('b');
      out.write('c');
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("<h3>Address Info</h3>\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("				<td>Street</td>\r\n");
      out.write("				<td>St1</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("			</table>");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
