/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-24 07:00:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ajax;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"assets/js/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		$('#buttonDemo1').click(function() {\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : 'GET',\r\n");
      out.write("				url : 'ajax1',\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					$('#result1').html(data)\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$('#buttonDemo2').click(function() {\r\n");
      out.write("			var fullName = $('#fullName').val();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : 'GET',\r\n");
      out.write("				url : 'ajax2',\r\n");
      out.write("				data : {\r\n");
      out.write("					fullName : fullName\r\n");
      out.write("				},\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					$('#result2').html(data)\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$('#buttonDemo3').click(function() {\r\n");
      out.write("			var userName = $('#userName').val();\r\n");
      out.write("			var passWord = $('#passWord').val();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : 'POST',\r\n");
      out.write("				url : 'ajax2',\r\n");
      out.write("				data : {\r\n");
      out.write("					userName : userName,\r\n");
      out.write("					passWord : passWord\r\n");
      out.write("				},\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					$('#result3').html(data)\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		})\r\n");
      out.write("\r\n");
      out.write("		$('#buttonDemo4').click(function() {\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : 'POST',\r\n");
      out.write("				url : 'ajax3',\r\n");
      out.write("				success : function(product) {\r\n");
      out.write("					var s = 'id: ' + product.id;\r\n");
      out.write("					s += '<br> name: ' + product.name;\r\n");
      out.write("					s += '<br> quantity: ' + product.quantity;\r\n");
      out.write("					s += '<br> status: ' + product.status;\r\n");
      out.write("					s += '<br> photo: ' + product.photo;\r\n");
      out.write("					s += '<br> category id: ' + product.category.id;\r\n");
      out.write("					s += '<br> category name: ' + product.category.name;\r\n");
      out.write("					$('#result4').html(s)\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$('#buttonDemo5').click(function() {\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : 'POST',\r\n");
      out.write("				url : 'ajax4',\r\n");
      out.write("				success : function(products) {\r\n");
      out.write("					var s = '';\r\n");
      out.write("					for (var i = 0; i < products.length; i++) {\r\n");
      out.write("						s += '<tr>';\r\n");
      out.write("						s += '<td>' + products[i].id + '</td>';\r\n");
      out.write("						s += '<td>' + products[i].name + '</td>';\r\n");
      out.write("						s += '<td>' + products[i].category.id + '</td>';\r\n");
      out.write("						s += '<td>' + products[i].category.name + '</td>';\r\n");
      out.write("						s += '</tr>';\r\n");
      out.write("					}\r\n");
      out.write("					$('#mytable tbody').html(s)\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>AJAX</h1>\r\n");
      out.write("	<input type=\"button\" value=\"Demo 1\" id=\"buttonDemo1\">\r\n");
      out.write("	<br>\r\n");
      out.write("	<span id=\"result1\"></span>\r\n");
      out.write("\r\n");
      out.write("	<h3>AJAX 2</h3>\r\n");
      out.write("	Full Name\r\n");
      out.write("	<input type=\"text\" id=\"fullName\">\r\n");
      out.write("	<input type=\"button\" value=\"Demo 2\" id=\"buttonDemo2\">\r\n");
      out.write("	<br>\r\n");
      out.write("	<span id=\"result2\"></span>\r\n");
      out.write("\r\n");
      out.write("	<h3>AJAX 3</h3>\r\n");
      out.write("	UserName\r\n");
      out.write("	<input type=\"text\" id=\"userName\"> Password\r\n");
      out.write("	<input type=\"password\" id=\"passWord\">\r\n");
      out.write("	<input type=\"button\" value=\"Login\" id=\"buttonDemo3\">\r\n");
      out.write("	<br>\r\n");
      out.write("	<span id=\"result3\"></span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<h1>AJAX 4</h1>\r\n");
      out.write("	<input type=\"button\" value=\"Demo 4\" id=\"buttonDemo4\">\r\n");
      out.write("	<br>\r\n");
      out.write("	<span id=\"result4\"></span>\r\n");
      out.write("\r\n");
      out.write("	<h1>AJAX 5</h1>\r\n");
      out.write("	<input type=\"button\" value=\"Demo 5\" id=\"buttonDemo5\">\r\n");
      out.write("\r\n");
      out.write("	<table id=\"mytable\" border=\"1\">\r\n");
      out.write("		<thead>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>ID</th>\r\n");
      out.write("				<th>Name</th>\r\n");
      out.write("				<th>Category ID</th>\r\n");
      out.write("				<th>Category Name</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</thead>\r\n");
      out.write("		<tbody>\r\n");
      out.write("		</tbody>\r\n");
      out.write("	</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
