package com.demo.entities;
// Generated Sep 13, 2023, 9:00:37 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Khoa generated by hbm2java
 */
@Entity
@Table(name = "khoa", catalog = "datlichkhambenh")
public class Khoa implements java.io.Serializable {

	private Integer makhoa;
	private String tenkhoa;
	private Set<Bacsi> bacsis = new HashSet<Bacsi>(0);

	public Khoa() {
	}

	public Khoa(String tenkhoa) {
		this.tenkhoa = tenkhoa;
	}

	public Khoa(String tenkhoa, Set<Bacsi> bacsis) {
		this.tenkhoa = tenkhoa;
		this.bacsis = bacsis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "makhoa", unique = true, nullable = false)
	public Integer getMakhoa() {
		return this.makhoa;
	}

	public void setMakhoa(Integer makhoa) {
		this.makhoa = makhoa;
	}

	@Column(name = "tenkhoa", nullable = false, length = 250)
	public String getTenkhoa() {
		return this.tenkhoa;
	}

	public void setTenkhoa(String tenkhoa) {
		this.tenkhoa = tenkhoa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khoa")
	public Set<Bacsi> getBacsis() {
		return this.bacsis;
	}

	public void setBacsis(Set<Bacsi> bacsis) {
		this.bacsis = bacsis;
	}

}
