package com.demo.entities;
// Generated Sep 13, 2023, 9:00:37 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lichkham generated by hbm2java
 */
@Entity
@Table(name = "lichkham", catalog = "datlichkhambenh")
public class Lichkham implements java.io.Serializable {

	private Integer id;
	private Bacsi bacsi;
	private Benhnhan benhnhan;
	private Date ngaykham;
	private String noidung;

	public Lichkham() {
	}

	public Lichkham(Bacsi bacsi, Benhnhan benhnhan, Date ngaykham, String noidung) {
		this.bacsi = bacsi;
		this.benhnhan = benhnhan;
		this.ngaykham = ngaykham;
		this.noidung = noidung;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mabs", nullable = false)
	public Bacsi getBacsi() {
		return this.bacsi;
	}

	public void setBacsi(Bacsi bacsi) {
		this.bacsi = bacsi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mabn", nullable = false)
	public Benhnhan getBenhnhan() {
		return this.benhnhan;
	}

	public void setBenhnhan(Benhnhan benhnhan) {
		this.benhnhan = benhnhan;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaykham", nullable = false, length = 10)
	public Date getNgaykham() {
		return this.ngaykham;
	}

	public void setNgaykham(Date ngaykham) {
		this.ngaykham = ngaykham;
	}

	@Column(name = "noidung", nullable = false, length = 65535)
	public String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

}
